Tech Project/employee-reimbursement-project/P2TestPlan.md

P2 Test Plan

---

Tech Project/employee-reimbursement-project/employee-reimbursement/pom.xml
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/ManagerTable.java

Set up hibernate. Started Manager table and updated pom.

Set up hibernate and manager table entity/ & pom

---

P2-Tables.sql
Tech Project/employee-reimbursement-project/employee-reimbursement/pom.xml
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/repository/AAATable.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/repository/ReimbursementTable.java

Initial setup changes

---

P2-Tables.sql
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/AAA.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/Reimbursement.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/AAADAOInterface.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/AAADao.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/AAATest.java

Entities, 1 DAO & 1 DAO interface base setup

Entities, 1 DAO & 1 DAO interface base setup

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/utils/HibernateUtil.java

created HibernateUtil class that my DAOs can use

created HibernateUtil class that my DAOs can use

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/Reimbursement.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/AAADAOInterface.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/AAADao.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/utils/HibernateUtil.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/AAATest.java

AAA unit test/create request & get requests

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/AAADAOInterface.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/AAADao.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/AAATest.java

Completed AAA unit test unless we have to add Login testing here.

Completed AAAtest, may need Login test

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/AAATest.java

Need reimbursment unit test. Moving on to service test for AAA

AAA last push for now

---

P2-Tables.sql
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/Reimbursement.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/EmployeesDao.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/EmployeesService.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/EmployeesTest.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/service/EmployeesServiceTest.java

This should be the most updated stuff

Mostupdatedstuffrepository

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/Reimbursement.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/ReimbursementDAOInterface.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/repository/ReimbursementDao.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/EmployeesService.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/ReimbursementTest.java

"david branch"

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/entities/Reimbursement.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/exceptions/InvalidRequest.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/ReimbursementServiceInterface.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/ReimbursementServices.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/service/ReimbursementServiceTest.java

reimbursement update

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/EmployeesService.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/EmployeesServiceInterface.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/EmployeesTest.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/repository/ReimbursementTest.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/service/EmployeesServiceTest.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/service/ReimbursementServiceTest.java

NEXT UP API. Starting tomorrow

Unit-Service-COMPLETE

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/Main.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/controllers/EmployeesController.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/EmployeesService.java

Employee api section done but might need to adjust the update and create (wasn't able to test it in postman bc my version of java 1.7 didn't cooperate with lambdas (need 1.8). I'll ask eric to help with that tomorrow. I followed his video to a T so it should be working.

Employees section of API complete(might need change)

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/Main.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/controllers/EmployeesController.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/controllers/ReimbursementController.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/ReimbursementServiceInterface.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/services/ReimbursementServices.java

Reimbursement Controller/Main.java
Employees Controller updated

API Updated

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/Main.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/controllers/EmployeesController.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/java/com/project2/controllers/ReimbursementController.java

made end points in api more Restful

---

Tech Project/employee-reimbursement-project/employee-reimbursement/pom.xml
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/runner/TestRunner.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Employee.feature
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Login.feature
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Manager.feature

started the feature files but i cannot get maven to spit out the steps snippets need help!!

start of the automation test

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Employee.feature
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Manager.feature

Updated features(only one feature per file)

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/manager.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/style.css

html and css are now updated with no spaces on favorite

no spaces now

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/poms/Employee.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/runner/TestRunner.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/steps/EmployeeSteps.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/steps/LoginSteps.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/steps/ManagerSteps.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Employee.feature

updated feature file poms test runner and steps

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/P2Employee.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/employee.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/login.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/service/EmployeesServiceTest.java

Updated login/employee/employeesServiceTest

Updated employee/login/employeesServucetest

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/steps/LoginSteps.java

login set up java for OG login html

new login setup

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/login.html

login button & password updated to match css

updated login.html

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/P2Manager.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/employee.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/login.html

logouts in manager and employee page now

Logouts implemented

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/P2Manager.html

css added to P2Manager.html

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/P2Manager.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/style.css

heading matches on table for Id, amount, etc when table populates, corrected the css to fit

fixed css and html table head to match on table

---

Tech Project/employee-reimbursement-project/employee-reimbursement/src/main/resources/web pages/EMPLOYEEdavid.html
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/poms/Employee.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/steps/EmployeeSteps.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/steps/LoginSteps.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/java/com/project2/steps/ManagerSteps.java
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Employee.feature
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Login.feature
Tech Project/employee-reimbursement-project/employee-reimbursement/src/test/resources/features/Manager.feature

Fix 6 and then be done with it

Updated (6 Errors) left to fix
